-- ═══════════════════════════════════════════════
-- LUMIEE WEB STUDIO — DATABASE SCHEMA
-- Run this entire file in Supabase SQL Editor
-- ═══════════════════════════════════════════════


-- ── 1. ENQUIRIES ─────────────────────────────────
-- Every form submission from a potential client
CREATE TABLE enquiries (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),

  -- what they selected
  service TEXT NOT NULL, -- website | mobile | design | seo
  stage TEXT NOT NULL,   -- enquiry | paid

  -- basic contact (always collected)
  full_name TEXT NOT NULL,
  whatsapp TEXT NOT NULL,
  email TEXT,

  -- all form fields stored as flexible JSON
  form_data JSONB NOT NULL DEFAULT '{}',

  -- agent workflow status
  status TEXT NOT NULL DEFAULT 'new',
  -- new → draft_ready → awaiting_approval → reply_sent → paid → onboarded

  -- Agent 1 output
  agent_reply TEXT,          -- the drafted reply
  invoice_url TEXT,          -- link to generated PDF invoice
  paystack_link TEXT,        -- payment link sent to client
  paystack_amount INTEGER,   -- amount in kobo

  -- payment tracking
  payment_ref TEXT,
  payment_verified BOOLEAN DEFAULT FALSE,
  paid_at TIMESTAMPTZ,

  -- approval tracking
  approved_by_owner BOOLEAN DEFAULT FALSE,
  approved_at TIMESTAMPTZ,
  reply_sent_at TIMESTAMPTZ
);


-- ── 2. CLIENTS ───────────────────────────────────
-- Created automatically when payment is confirmed
CREATE TABLE clients (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),

  enquiry_id UUID REFERENCES enquiries(id),

  full_name TEXT NOT NULL,
  email TEXT,
  whatsapp TEXT NOT NULL,
  business_name TEXT,
  business_address TEXT,

  -- brand assets
  brand_colors TEXT,
  brand_fonts TEXT,
  social_handles TEXT,
  has_logo BOOLEAN DEFAULT FALSE,

  -- onboarding form submitted?
  onboarding_complete BOOLEAN DEFAULT FALSE,
  onboarding_data JSONB DEFAULT '{}',
  onboarded_at TIMESTAMPTZ,

  notes TEXT -- your private notes about this client
);


-- ── 3. PROJECTS ──────────────────────────────────
-- One project per client engagement
CREATE TABLE projects (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),

  client_id UUID REFERENCES clients(id),
  enquiry_id UUID REFERENCES enquiries(id),

  title TEXT NOT NULL,
  service TEXT NOT NULL, -- website | mobile | design | seo
  description TEXT,

  -- project stage
  stage TEXT NOT NULL DEFAULT 'onboarding',
  -- onboarding → in_progress → review → delivered

  -- brief generated by Agent 3
  project_brief TEXT,
  brief_generated_at TIMESTAMPTZ,

  -- timeline
  deadline DATE,
  delivered_at TIMESTAMPTZ,

  -- your private notes
  notes TEXT
);


-- ── 4. AGENT LOGS ────────────────────────────────
-- Every agent action is logged for debugging and audit
CREATE TABLE agent_logs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),

  agent TEXT NOT NULL,      -- intake | payment | onboarding
  action TEXT NOT NULL,     -- what the agent did
  enquiry_id UUID REFERENCES enquiries(id),
  client_id UUID REFERENCES clients(id),
  project_id UUID REFERENCES projects(id),

  status TEXT NOT NULL,     -- success | error
  details JSONB DEFAULT '{}',
  error_message TEXT
);


-- ── 5. APPROVAL QUEUE ────────────────────────────
-- Holds Agent 1 drafts waiting for your approval
CREATE TABLE approval_queue (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),

  enquiry_id UUID REFERENCES enquiries(id),

  draft_reply TEXT NOT NULL,
  invoice_url TEXT,
  paystack_link TEXT,

  status TEXT NOT NULL DEFAULT 'pending',
  -- pending → approved → edited_and_approved → rejected

  -- if you edited the reply before approving
  edited_reply TEXT,
  approval_token TEXT UNIQUE, -- used in the WhatsApp approve link

  resolved_at TIMESTAMPTZ
);


-- ── 6. NOTIFICATIONS ─────────────────────────────
-- Log of every WhatsApp and email notification sent
CREATE TABLE notifications (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),

  type TEXT NOT NULL,       -- whatsapp | email
  recipient TEXT NOT NULL,  -- owner | client
  to_number TEXT,
  to_email TEXT,
  subject TEXT,
  message TEXT NOT NULL,
  status TEXT NOT NULL,     -- sent | failed
  error_message TEXT,

  enquiry_id UUID REFERENCES enquiries(id),
  client_id UUID REFERENCES clients(id)
);


-- ═══════════════════════════════════════════════════
-- ROW LEVEL SECURITY
-- Locks everything down so only your backend can read/write
-- ═══════════════════════════════════════════════════

ALTER TABLE enquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE approval_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- Service role (your Netlify functions) can do everything
CREATE POLICY "service_role_all_enquiries" ON enquiries FOR ALL USING (true);
CREATE POLICY "service_role_all_clients" ON clients FOR ALL USING (true);
CREATE POLICY "service_role_all_projects" ON projects FOR ALL USING (true);
CREATE POLICY "service_role_all_logs" ON agent_logs FOR ALL USING (true);
CREATE POLICY "service_role_all_approvals" ON approval_queue FOR ALL USING (true);
CREATE POLICY "service_role_all_notifications" ON notifications FOR ALL USING (true);


-- ═══════════════════════════════════════════════════
-- INDEXES — speeds up common queries
-- ═══════════════════════════════════════════════════

CREATE INDEX idx_enquiries_status ON enquiries(status);
CREATE INDEX idx_enquiries_service ON enquiries(service);
CREATE INDEX idx_enquiries_payment_ref ON enquiries(payment_ref);
CREATE INDEX idx_clients_enquiry ON clients(enquiry_id);
CREATE INDEX idx_projects_client ON projects(client_id);
CREATE INDEX idx_projects_stage ON projects(stage);
CREATE INDEX idx_approval_token ON approval_queue(approval_token);
CREATE INDEX idx_agent_logs_agent ON agent_logs(agent);
